BASE: ['resnet18_base.yaml']
DATA:
  BATCH_SIZE: 128
  DATASET: "medium_imagenet"
  IMG_SIZE: 96
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NUM_CLASSES: 200
  NAME: suryapraknixnet
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 2
OUTPUT: "output/suryapraknixnet_medium_imagenet"
SAVE_FREQ: 1
PRINT_FREQ: 500
